### ISSUE TITLE
.clang-format seems to be invalid

### ISSUE THREAD

**Issue by kminoda** [koide3/ndt_omp#55]
[These four lines in .clang-format](https://github.com/koide3/ndt_omp/blob/01a07675953c9896001afd9ef1571efefc80cc82/.clang-format#L95-L98) seems to be invalid.
I think the correct way of writing would be

```
RawStringFormats:
  - Language: TextProto
    Delimiters:
      - pb
    BasedOnStyle: google
```

Please also refer to this PR: https://github.com/koide3/ndt_omp/pull/56
After applying this PR, we can run clang-format e.g. by `clang-format -i $FILE`
